# -*- coding: utf-8 -*-
"""Map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17zQuOjDGPhcEQ_QyXwNxQ2-753Hg7Ewc
"""

import folium
import pandas as pd
import branca

df = pd.read_csv("Heatmap.csv")


m = folium.Map(location=[20.593684, 78.96288],zoom_start=5,disable_3d=True)





def get_frame(url,width,height,loc,datee,sn,cb):
    html = """ 
            <!doctype html>
        <html>
    
        <img id="myIFrame" class="frame" width="{}px" height="{}px" src={}""".format(width,height,url) + """ frameborder="0" ></img>
         <p>scientific name :<b>{}</b>""".format(sn)+"""<br>date : <b>{}</b>""".format(datee)+"""<br>clicked by : <b>{}</b>""".format(cb)+"""<br>location : <b>{}</b>""".format(loc)+"""</p>
       
    
        <style>
     
        .frame {

            border: 0;
            
            overflow:hidden;
         
        }
        </style>
        </html>"""
    return html
for link,lat,lon,loc,datee,sn,cb in zip(df['img link'],df['latitude'],df['longitude'],df["location"],df['date'],df['scientific name'],df['clicked By']):

    popup = get_frame(link,
                      150,
                    150,loc,datee,sn,cb)
    iframe = branca.element.IFrame(html=popup,width=200,height=200)
    popup = folium.Popup(iframe,max_width=200)
    marker = folium.Marker([lat,lon],
                                popup=popup)

    marker.add_to(m)

m.save("Heatmap.html")

